# Generated by Django 5.2.13 on 2026-04-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ranga',
                'verbose_name_plural': 'Rangi',
                'ordering': ['min_score'],
            },
        ),
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('recent_trips', models.PositiveIntegerField(default=0)),
                ('diversity_score', models.PositiveIntegerField(default=0)),
                ('loyalty_score', models.PositiveIntegerField(default=0)),
                ('bonus_score', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stats', to='rankings.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statystyka użytkownika',
                'verbose_name_plural': 'Statystyki użytkowników',
                'ordering': ['-total_score', 'user__username'],
            },
        ),
    ]
