# Generated by Django 5.2.13 on 2026-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_userstat_current_streak_userstat_longest_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='max_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='min_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
