# Generated by Django 5.2.13 on 2026-04-18 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('badge_type', models.CharField(choices=[('automatic', 'Automatyczna'), ('manual', 'Ręczna'), ('seasonal', 'Sezonowa'), ('special', 'Specjalna')], default='automatic', max_length=20)),
                ('trigger_type', models.CharField(choices=[('trips_count', 'Liczba wyjazdów'), ('attendance_percent', 'Procent obecności'), ('consecutive_trips', 'Kolejne wyjazdy'), ('score', 'Wynik punktowy'), ('manual', 'Ręczne przyznanie')], default='manual', max_length=30)),
                ('trigger_value', models.PositiveIntegerField(blank=True, help_text='Wartość progu dla automatycznego przyznawania odznaki.', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Odznaka',
                'verbose_name_plural': 'Odznaki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='badges.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odznaka użytkownika',
                'verbose_name_plural': 'Odznaki użytkowników',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
