# Generated by Django 5.2.13 on 2026-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, help_text='Obrazek odznaki, najlepiej PNG, JPG albo WEBP.', null=True, upload_to='badges/'),
        ),
    ]
